### ISSUE TITLE
does not detect mime type or decode metadata on files from linx

### ISSUE THREAD

**Issue by echarlie** [wuvt/johnny-six#13] opened 2020-07-31 17:12 UTC
for mp3s, it correctly guesses MAD and tries (but fails) to log empty metadata. for flack, it fails do decode at all

**Comment by echarlie** [comment] 2020-07-31 20:16
```Jul 31 12:50:00 flint docker[18920]: 2020/07/31 12:50:00 [procol.external:3] Failed to fetch mime-type for https://linx.apps.wuvt.vt.edu/selif/567l1eos.flac.
Jul 31 12:50:00 flint docker[18920]: 2020/07/31 12:50:00 [procol.external:3] No known file extension for mime:
Jul 31 12:50:05 flint docker[18920]: 2020/07/31 12:50:05 [decoder:3] Unable to decode "/tmp/liq-processc6bb33.osb" as {audio=1+;video=0;midi=0}!
Jul 31 12:50:05 flint docker[18920]: Certificate[1] subject=/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
Jul 31 12:50:05 flint docker[18920]: Certificate[1] issuer =/O=Digital Signature Trust Co./CN=DST Root CA X3
Jul 31 12:50:05 flint docker[18920]: SSL: rejecting connection - error=20
Jul 31 12:50:05 flint docker[18920]: 2020/07/31 12:50:05 [procol.external:3] Failed to fetch mime-type for https://linx.apps.wuvt.vt.edu/selif/txzmxzwf.mp3.
Jul 31 12:50:05 flint docker[18920]: 2020/07/31 12:50:05 [procol.external:3] No known file extension for mime:
Jul 31 12:50:07 flint docker[18920]: 2020/07/31 12:50:07 [decoder:3] Method "MAD" accepted "/tmp/liq-process4397ae.osb".
Jul 31 12:51:56 flint docker[18920]: 2020/07/31 12:51:56 [decoder:3] Method "FLAC" accepted "/tmp/liq-process065372.flac".
Jul 31 12:52:06 flint docker[18920]: 2020/07/31 12:52:06 [tracks:3] Prepared "/tmp/liq-process4397ae.osb" (RID 408).
Jul 31 12:52:06 flint docker[18920]: 2020/07/31 12:52:06 [fallback_8465:3] Switch to tracks with forgetful transition.
Jul 31 12:52:06 flint docker[18920]: 2020/07/31 12:52:06 [log_metadata:3] Artist= Title= Album= Label= DJ=
Jul 31 12:52:06 flint docker[18920]: Certificate[1] subject=/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
Jul 31 12:52:06 flint docker[18920]: Certificate[1] issuer =/O=Digital Signature Trust Co./CN=DST Root CA X3
Jul 31 12:52:06 flint docker[18920]: SSL: rejecting connection - error=20
```

**Comment by mutantmonkey** [comment] 2020-08-05 04:01
There appears to be some sort of issue with the network request (URL redacted). When running liquidsoap with `--debug`, I get the following output:
```
2020/08/04 19:32:58 [procol.external:3] Failed to fetch mime-type for https://[our linx]/selif/urey6pa9.flac.
2020/08/04 19:32:58 [procol.external:4] Request response: (("Internal error", 999, "Internal error"), [], "Error while processing request: SSL read() error: error:00000000:lib(0):func(0):reason(0)")
2020/08/04 19:32:58 [procol.external:3] No known file extension for mime: 
2020/08/04 19:32:58 [protocol.process:4] Processing osb,curl -sL "https$(colon)//[our linx]/selif/urey6pa9.flac" -o $(output)
2020/08/04 19:32:58 [lang:4] Executing curl -sL "https://[our linx]/selif/urey6pa9.flac" -o "/tmp/liq-processae03c9.osb"
```

I need to do some more testing, perhaps with a Linx instance that's not behind our auth proxy, but right now I'm thinking this may be due to some issue with SSO.

**Comment by echarlie** [comment] 2020-08-05 20:43
Per discussion on slack, potentially a permutation of https://github.com/buzzfeed/sso/issues/232

**Comment by mutantmonkey** [comment] 2020-08-06 06:22
See also https://github.com/buzzfeed/sso/issues/151 which has a better analysis of the problem, although the root cause is probably identical to buzzfeed/sso#232.

**Comment by mutantmonkey** [comment] 2020-08-06 06:39
Making some more progress on this, it seems Liquidsoap is doing a HEAD with the internal HTTP client first, which is failing, possibly due to not sending SNI. Running with `--debug --verbose`:
```
2020/08/05 23:36:53 [procol.external:4] Fetching https head for https://[,,,[/selif/urey6pa9.flac
Certificate[2] subject=/O=Digital Signature Trust Co./CN=DST Root CA X3
Certificate[2] issuer =/O=Digital Signature Trust Co./CN=DST Root CA X3
Certificate[1] subject=/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
Certificate[1] issuer =/O=Digital Signature Trust Co./CN=DST Root CA X3
Certificate[0] subject=/CN=am.wuvt.vt.edu
Certificate[0] issuer =/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
2020/08/05 23:36:53 [procol.external:3] Failed to fetch mime-type for https://linx.apps.wuvt.vt.edu/selif/urey6pa9.flac.
2020/08/05 23:36:53 [procol.external:4] Request response: (("Internal error", 999, "Internal error"), [], "Error while processing request: SSL read() error: error:00000000:lib(0):func(0):reason(0)")
```

Note the `am.wuvt.vt.edu` certificate...

Edit: Indeed. Fixed 5 days ago: https://github.com/savonet/liquidsoap/issues/1304

**Comment by mutantmonkey** [comment] 2020-08-10 00:35
We're running Liquidsoap v1.4.3-pre-release for now which should fix this. I'd like to do some testing before closing this out, though.

**Comment by mutantmonkey** [comment] 2020-08-10 01:20
Just confirmed with a FLAC file; seems to be working fine. If we continue to see problems with metadata on certain MP3 files, let's open a new issue.

**Closed as completed by mutantmonkey** 2020-08-10 01:20 UTC
Labels: bug, upstream-issue
